# Generated by Django 4.2 on 2024-07-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('apellidos_nombres', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('provincia', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('id_estado_cliente', models.IntegerField()),
                ('telefono', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
