# Generated by Django 4.2 on 2024-08-03 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.CharField(blank=True, max_length=30, null=True)),
                ('item_catalogo', models.CharField(blank=True, max_length=30, null=True)),
                ('id_raiz', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ano_lanzamiento', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('id_estado_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_productos', to='videojuegos.catalogos')),
                ('id_formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='videojuegos.catalogos')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='videojuegos.catalogos')),
                ('id_plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas', to='videojuegos.catalogos')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto_1', models.IntegerField(blank=True, null=True)),
                ('cantidad_producto_2', models.IntegerField(blank=True, null=True)),
                ('cantidad_producto_3', models.IntegerField(blank=True, null=True)),
                ('cantidad_producto_4', models.IntegerField(blank=True, null=True)),
                ('cantidad_producto_5', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='videojuegos.clientes')),
                ('id_producto_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_1', to='videojuegos.inventario')),
                ('id_producto_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_2', to='videojuegos.inventario')),
                ('id_producto_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_3', to='videojuegos.inventario')),
                ('id_producto_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_4', to='videojuegos.inventario')),
                ('id_producto_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_5', to='videojuegos.inventario')),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='RegistroVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_ventas', to='videojuegos.catalogos')),
                ('id_forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='videojuegos.catalogos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_ventas', to='videojuegos.ventas')),
            ],
            options={
                'db_table': 'registro_ventas',
            },
        ),
        migrations.AlterField(
            model_name='clientes',
            name='id_estado_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='videojuegos.catalogos'),
        ),
    ]
