# Generated by Django 4.2 on 2024-08-03 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0002_catalogos_inventario_ventas_registroventas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id_estado_cliente',
            field=models.ForeignKey(db_column='id_estado_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='videojuegos.catalogos'),
        ),
    ]
