# Generated by Django 4.2 on 2024-08-03 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0003_alter_clientes_id_estado_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_estado_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_estado_producto', to='videojuegos.catalogos'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_formato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_formato', to='videojuegos.catalogos'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_genero', to='videojuegos.catalogos'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_plataforma', to='videojuegos.catalogos'),
        ),
    ]
