# Generated by Django 4.2 on 2024-08-03 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0004_alter_inventario_id_estado_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='id_estado_producto',
            field=models.ForeignKey(db_column='id_estado_producto', on_delete=django.db.models.deletion.CASCADE, related_name='estados_productos', to='videojuegos.catalogos'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_formato',
            field=models.ForeignKey(db_column='id_formato', on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='videojuegos.catalogos'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_genero',
            field=models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='videojuegos.catalogos'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id_plataforma',
            field=models.ForeignKey(db_column='id_plataforma', on_delete=django.db.models.deletion.CASCADE, related_name='plataformas', to='videojuegos.catalogos'),
        ),
    ]
