# Generated by Django 4.2 on 2024-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0006_inventario_codigo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='codigo_producto',
            field=models.CharField(max_length=10),
        ),
    ]
