# Generated by Django 4.2 on 2024-08-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0007_alter_inventario_codigo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroventas',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cliente',
        ),
        migrations.AddField(
            model_name='registroventas',
            name='id_productos_vendidos',
            field=models.ForeignKey(db_column='id_productos_vendidos', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='registro_ventas', to='videojuegos.ventas'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='videojuegos.clientes'),
        ),
        migrations.AlterField(
            model_name='registroventas',
            name='id_estado_venta',
            field=models.ForeignKey(db_column='id_estado_venta', on_delete=django.db.models.deletion.CASCADE, related_name='estados_ventas', to='videojuegos.catalogos'),
        ),
        migrations.AlterField(
            model_name='registroventas',
            name='id_forma_pago',
            field=models.ForeignKey(db_column='id_forma_pago', on_delete=django.db.models.deletion.CASCADE, related_name='formas_pago', to='videojuegos.catalogos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_producto_1',
            field=models.ForeignKey(blank=True, db_column='id_producto_1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_1', to='videojuegos.inventario'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_producto_2',
            field=models.ForeignKey(blank=True, db_column='id_producto_2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_2', to='videojuegos.inventario'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_producto_3',
            field=models.ForeignKey(blank=True, db_column='id_producto_3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_3', to='videojuegos.inventario'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_producto_4',
            field=models.ForeignKey(blank=True, db_column='id_producto_4', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_4', to='videojuegos.inventario'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_producto_5',
            field=models.ForeignKey(blank=True, db_column='id_producto_5', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_producto_5', to='videojuegos.inventario'),
        ),
    ]
